export const cities = [
  { label: 'Santa Rita do Sapucaí', value: 'santa-rita-do-sapucai' },
  { label: 'Piquete', value: 'piquete' },
  { label: 'Paraisópolis', value: 'paraisopolis' },
  { label: 'Campos do Jordão', value: 'campos-do-jordao' },
  { label: 'Lorena', value: 'lorena' },
  { label: 'Passa Quatro', value: 'passa-quatro' },
  { label: 'Guaratinguetá', value: 'guaratingueta' },
  { label: 'Lambari', value: 'lambari' },
  { label: 'Aparecida', value: 'aparecida' },
  { label: 'Cruzeiro', value: 'cruzeiro' },
  { label: 'São Lourenço', value: 'sao-lourenco' },
  { label: 'Pouso Alegre', value: 'pouso-alegre' },
  { label: 'Itanhandu', value: 'itanhandu' },
  { label: 'Pindamonhangaba', value: 'pindamonhangaba' },
  { label: 'Tremembé', value: 'tremembe' },
  { label: 'São Gonçalo do Sapucaí', value: 'sao-goncalo-do-sapucai' },
  { label: 'Cambuí', value: 'cambui' },
  { label: 'Campanha', value: 'campanha' },
  { label: 'Cambuquira', value: 'cambuquira' },
  { label: 'Taubaté', value: 'taubate' },
  { label: 'Conceição do Rio Verde', value: 'conceicao-do-rio-verde' }
]

export const statesBR = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO'
]
